# Generated by Django 2.1.3 on 2018-12-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20181130_2015'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='career',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='career', to='subject.Subject'),
        ),
    ]
